# Training configuration
GPU: [0,1,2,3]

VERBOSE: False

MODEL:
  MODE: 'ULCFNET'

# Optimization arguments.
OPTIM:
  BATCH: 4
  EPOCHS: 2
  # EPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: '.\datasets\LUIE\train'       # path to training data
  VAL_DIR: '.\datasets\LUIE\test'          # path to validation data
  SAVE_DIR: './checkpoints_ULCFNet'           # path to save models and images
